version: "3.7"
services:
  db:
    image: mongo:latest # Verwende die neueste Version von MongoDB
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: dhbw-stuttgart-2023 # Root-Benutzername für MongoDB
      MONGO_INITDB_ROOT_PASSWORD: NiBEr650294_X # Root-Passwort für MongoDB
    #volumes:
    #- ./api/db/data:/data/db # Mount-Pfad für MongoDB-Daten
    restart: always
    networks:
      - website-network

  api:
    image: controller-image-test
    container_name: node-container
    restart: always
    volumes:
      - ./Controller/api-website-dhbw:/home/node/app
    ports:
      - "5000:5000"

    depends_on:
      - db
    networks:
      - website-network

  web:
    image: php:apache
    ports:
      - "9000:80"
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./View/
        - action: sync
          path: ./View
          target: /var/www/html/
    volumes:
      - ./View:/var/www/html/
    depends_on:
      - db
      - api
    networks:
      - website-network

networks:
  website-network:
    driver: bridge
